### ISSUE TITLE
Takes 9.5 seconds to respond

### ISSUE THREAD

**Issue by mightyiam** [lomirus/live-server#7] opened 2022-09-10 10:28 UTC
I don't have any other hints... You can try yourself here, though:
https://github.com/mobusoperandi/mobusoperandi.github.io

```
$ cargo bin makers dev
```

![2022-09-10_10-16](https://user-images.githubusercontent.com/635591/189479236-74ce0080-b7a7-4e6d-b1b8-6962e894e152.png)

**Comment by lomirus** [comment] 2022-09-10 15:29
![](https://i.imgur.com/3AzbkzA.png)

Sorry but I cannot reproduce this problem. Is it always like that on your PC? And what's your version.
(Edit: I didn't notice your repository you mentioned when I sending this comment 😂)

**Comment by lomirus** [comment] 2022-09-10 15:33
I just cloned your repository to my computer and ran the `cargo bin makers dev`. But it shows
```
error: no such subcommand: `bin`

        Did you mean `b`?
```
Do I need to install somethings?

**Comment by mightyiam** [comment] 2022-09-10 17:12
Yes. Sorry. That is from the `cargo-run-bin` package.

```
$ cargo install cargo-run-bin
```

And I know it seems like it's halting but it's actually building without providing output.

**Comment by lomirus** [comment] 2022-09-12 04:46
```
$ pwd
/tmp/mobusoperandi.github.io

$ cargo bin makers dev
[cargo-make] INFO - makers 0.36.0
[cargo-make] INFO - Project: _
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: dev
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: watch
[cargo-make] INFO - Execute Command: "/usr/bin/env" "bash" "/tmp/fsio_eJWd87ZO0v.sh"
[cargo-make] INFO - Running Task: html
[cargo-make] INFO - Execute Command: "/usr/bin/env" "bash" "/tmp/fsio_VsI7qGdDYD.sh"
/tmp/fsio_VsI7qGdDYD.sh: line 3: OUTPUT_DIR: unbound variable
[cargo-make] ERROR - Unable to execute script.
[cargo-make] WARN - Build Failed.
+ cargo bin cargo-watch --shell 'cargo bin makers produce_output'

$ cargo run
   Compiling _ v0.0.0 (/tmp/mobusoperandi.github.io)
error: environment variable `OUTPUT_DIR` not defined
  --> src/main.rs:15:45
   |
15 |     let output_dir: PathBuf = PathBuf::from(env!("OUTPUT_DIR"));
   |                                             ^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: use of unstable library feature 'path_try_exists'
  --> src/main.rs:39:41
   |
39 |                     if output_file_path.try_exists().unwrap() {
   |                                         ^^^^^^^^^^
   |
   = note: see issue #83186 <https://github.com/rust-lang/rust/issues/83186> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `_` due to 2 previous errors
```

I cannot run your project.

**Comment by mightyiam** [comment] 2022-09-12 09:39
Sorry about that. It's not a documented project.

Flip the comment between [these two lines](https://github.com/mobusoperandi/mobusoperandi.github.io/blob/601cffe14f965aa1272ca546fdf58061a2190e15/Makefile.toml#L89-L90).

```
$ cargo install cargo-run-bin
$ export OUTPUT_DIR="output"
$ cargo bin makers produce_output
$ cargo bin makers serve
```

The last command starts live-server.

**Comment by lomirus** [comment] 2022-09-13 05:26
The reason of this is that this html file is too big and thus consumes a lot of time to parse. Maybe the injection mechanism can be improved. I will try to fix this later.

**Comment by lomirus** [comment] 2022-09-13 05:58
It should be fixed now. I just tested it and it responded in 5ms in my computer.

**Closed as completed by lomirus** 2022-09-13 05:58 UTC
Labels: bug

**Comment by mightyiam** [comment] 2022-09-13 07:46
Parse? It parses?

**Comment by mightyiam** [comment] 2022-09-13 07:47
Oh, for injecting the reloading script...

**Comment by mightyiam** [comment] 2022-09-13 15:13
Works great. Thank you, @lomirus .
